print("Executing KissMP modScript...")
loadJsonMaterialsFile("art/shapes/kissmp_playermodels/main.materials.json")

setExtensionUnloadMode("kissplayers", "manual")
setExtensionUnloadMode("kissghosts", "manual")
setExtensionUnloadMode("vehiclemanager", "manual")
setExtensionUnloadMode("kisstransform", "manual")
setExtensionUnloadMode("kissui", "manual")
setExtensionUnloadMode("kissmods", "manual")
setExtensionUnloadMode("kissrichpresence", "manual")
setExtensionUnloadMode("network", "manual")
setExtensionUnloadMode("kissconfig", "manual")
setExtensionUnloadMode("kissvoicechat", "manual")
