use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let version_str = env!("CARGO_PKG_VERSION");
    let parts: Vec<u32> = version_str.split('.')
        .map(|s| s.parse().unwrap_or(0))
        .collect();
    let major = parts[0];
    let minor = parts[1];
    
    // Generate Lua version file
    let lua_version_content = format!(
        "-- Generated by shared/build.rs\nlocal M = {{}}\nM.VERSION_STR = \"{}\"\nM.VERSION = {{ {}, {} }}\nreturn M\n",
        version_str, major, minor
    );
    
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let lua_file_path = Path::new(&manifest_dir).parent().unwrap().join("KISSMultiplayer/lua/ge/extensions/version.lua");
    
    // Create directory if it doesn't exist
    if let Some(parent) = lua_file_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    
    let _ = fs::write(lua_file_path, lua_version_content);

    // Generate Rust version file
    let rust_version_content = format!(
        "// Generated by shared/build.rs\npub const VERSION: (u32, u32) = ({}, {});\npub const VERSION_STR: &str = \"{}\";\n",
        major, minor, version_str
    );
    let rust_file_path = Path::new(&manifest_dir).join("src/version_gen.rs");
    let _ = fs::write(rust_file_path, rust_version_content);
}
